/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loansystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Kannawat
 */
public class loanMDI extends javax.swing.JFrame {
    fmLogin fm = null;
    LoanData_user fm2 = null;
    LoanData_search fm3 = null;
    UserLogin user = new UserLogin();
    /**
     * Creates new form loanMDI
     */
    public loanMDI() {
        initComponents();
        fmLoginDisplay();
        menuBar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        userInfoItem = new javax.swing.JMenuItem();
        searchMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Menu");

        userInfoItem.setMnemonic('s');
        userInfoItem.setText("UserInfo");
        userInfoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInfoItemActionPerformed(evt);
            }
        });
        fileMenu.add(userInfoItem);

        searchMenuItem.setMnemonic('a');
        searchMenuItem.setText("Search");
        searchMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(searchMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void userInfoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInfoItemActionPerformed
        resetForm(fm2, fm3);
        
        fm2 = new LoanData_user();
        desktopPane.add(fm2);
        fm2.setVisible(true);
        fm2.pack();
    }//GEN-LAST:event_userInfoItemActionPerformed

    private void searchMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMenuItemActionPerformed
        resetForm(fm2, fm3);
        
        fm3 = new LoanData_search();
        desktopPane.add(fm3);
        fm3.setVisible(true);
        fm3.pack();
    }//GEN-LAST:event_searchMenuItemActionPerformed
    
    private void fmLoginDisplay() {
        if(fm == null) {
            fm = new fmLogin(new LoginListener(){
                @Override
                public void LoginValue(String pName,String pPass){
                    if(pName.equals(user.getName()) && 
                        pPass.equals(user.getPassword()))
                    {
                        fm.dispose();
                        fm2 = new LoanData_user();
                        desktopPane.add(fm2);
                        fm2.setVisible(true);
                        fm2.pack();
                        menuBar.setVisible(true);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Check Username and Password");
                    }
                }
            });
            desktopPane.add(fm);
            fm.pack();
        }
        fm.setVisible(true); 
    }
    
    private void resetForm(LoanData_user pFm1, LoanData_search pFm2) {
        if(pFm1 != null) {
            pFm1.dispose();
        }
        if(pFm2 != null) {
            pFm2.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loanMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loanMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loanMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loanMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loanMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem searchMenuItem;
    private javax.swing.JMenuItem userInfoItem;
    // End of variables declaration//GEN-END:variables

}
